### ISSUE TITLE
Remove Skidded Code

### ISSUE THREAD

**Issue by smintf** [Gsnipe1blookethacks/Blookethack-menu#2]
Delete this repo or merge this [pull request](https://github.com/Gsnipe1blookethacks/Blookethack-menu/pull/1)

**Comment by Gsnipe1blookethacks** [comment]
Hope your happy

**Comment by smintf** [comment]
I'm tired of your bs.

**Comment by Gsnipe1blookethacks** [comment]
What did I do I did exactly what you said
